### PR TITLE
Efficient storage of cats on disk

### PR DESCRIPTION
**Pull request by mikedep333**
I'm thinking "How Catello stores content on filesystem" might be funnier. Since it implies the cats are being filed. Wording suggestions?

### CODE REVIEW

**Comment by waldenraines** [comment]
This project isn't accepting pull requests. Code is supposed to be force pushed straight to master. To that end, I've given you admin access.

**Comment by mikedep333** [comment]
@waldenraines :purr:, thank you for the admin access!

**Comment by mikedep333** [comment]
@waldenraines Are you sure I have admin access? I cannot push to origin.

**Comment by waldenraines** [comment]
> @waldenraines Are you sure I have admin access? I cannot push to origin.

I sent you an invitation that you must accept first I believe.

**Pull request closed without merging**
